### PR TITLE
fix(responsive): exchange form is user friendly on mobile

### LINKED ISSUE #1386: fix(responsive):exchange form
Exchange form is not user friendly on mobile.

### PR DESCRIPTION
**Pull request by JNSPK**
fixes #1386

### CODE REVIEW

File: packages/@1/ui/react/src/form/atom.ts [hunk 1]
```diff
@@ -74,19 +74,25 @@ export const input = tv({
...
   disabled:pointer-events-none
   disabled:opacity-50
+  md:flex-row
+  md:items-center
   [&>label]:flex
   [&>label]:items-center
   [&>label]:space-x-3
   `,
+  variants: {
+    mobileFlex: {
```
Comment (douglasduteil) [inline packages/@1/ui/react/src/form/atom.ts:92]:
```suggestion
    horizontal: {
```

File: packages/@1/modules/exchange/ui/src/form/new_exchange.tsx [hunk 2]
```diff
@@ -164,18 +164,20 @@ export function Exchange_CreateForm<
         />
       </label>
 
-      <fieldset className={fieldset()}>
-        <label>
-          <span>Sans échange</span>{" "}
+      <fieldset className={fieldset({ mobileFlex: true })}>
```
Comment (douglasduteil) [inline packages/@1/modules/exchange/ui/src/form/new_exchange.tsx:167]:
```suggestion
      <fieldset className={fieldset({ horizontal: true })}>
```

**Review by douglasduteil — CHANGES_REQUESTED** [review]

**Comment by douglasduteil** [comment]
I propose that we rename `mobileFlex` to `horizontal`

**Review by douglasduteil — APPROVED** [review]
