### PR TITLE
fix(ui): improvement for mobile responsiveness

### LINKED ISSUE #1468: fix(responsive): problem on message view and thread

### PR DESCRIPTION
**Pull request by JNSPK**
fixes #1468

### CODE REVIEW

**Comment by douglasduteil** [comment]
Might want to rebase after https://github.com/toctocorg/toctoc/pull/147

File: packages/@1/ui/react/src/grid/atom.ts [hunk 1]
```diff
@@ -6,6 +6,8 @@ import { tv } from "tailwind-variants";
 
 export const column_screen = tv({
   base: `
+    max-h-[calc(100vh_-_theme(spacing.24
+    ))]
```
Comment (douglasduteil) [inline packages/@1/ui/react/src/grid/atom.ts:10]:
```suggestion
    max-h-[calc(100vh_-_theme(spacing.24))]
```

Will need to reorder with prettier.
Might be in conflict with `max-h-[calc(100vh_-_theme(spacing.32))]`

**Review by douglasduteil — CHANGES_REQUESTED** [review]

File: apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/page.tsx [hunk 2]
```diff
@@ -99,12 +99,11 @@ const layout = tv({
...
   slots: {
     body: `
-      max-h-[calc(100%_-_theme(spacing.64))]
+      max-h-full
       overflow-y-auto
       py-4
       pr-5
-      md:max-h-full
-    `,
+      `,
```
Comment (douglasduteil) [inline apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/page.tsx:106]:
```suggestion
    `,
```

**Review by douglasduteil — APPROVED** [review]
